version: 2

sources:

  - name: sap_adw
    description: This is a replica of the Postgres database used by our client.
    # Documenting only the data we will use in the data products
    tables:
      - name: address
        description: This table contains information about addresses.
        columns:
          - name: ADDRESSID
            description: Unique identifier for the address.
            tests:
              - not_null
              - unique
          - name: CITY
            description: City name.
          - name: STATEPROVINCEID
            description: Identifier for the state or province.

      - name: countryregion
        description: This table contains information about countries and regions.
        columns:
          - name: COUNTRYREGIONCODE
            description: Code for the country or region.
            tests:
              - not_null
              - unique
          - name: NAME
            description: Name of the country or region.

      - name: customer
        description: This table contains information about customers.
        columns:
          - name: CUSTOMERID
            description: Unique identifier for the customer.
            tests:
              - not_null
              - unique
          - name: PERSONID
            description: Foreign Key for the people associated with the customer.
          - name: STOREID
            description: Foreign Key for the store associated with the customer.
          - name: TERRITORYID
            description: Foreign Key for the region associated with the customer.

      - name: emailaddress
        description: This table lists contacts for both active and inactive customers.
        columns:
          - name: EMAILADDRESSID
            description: Unique identifier for emailaddress.
            tests:
              - not_null
              - unique
          - name: BUSINESSENTITYID
            description: Unique identifier for the person.
          - name: EMAILADDRESS
            description: Email address.

      - name: person
        description: This table contains information about people in the system.
        columns:
          - name: BUSINESSENTITYID
            description: Unique identifier for the person.
            tests:
              - not_null
              - unique
          - name: FIRSTNAME
            description: First name of the person.
          - name: LASTNAME
            description: Last name of the person.
          - name: EMAILPROMOTION
            description: Email marketing preferences.

      - name: product
        description: This table contains information about products.
        columns:
          - name: PRODUCTID
            description: Unique identifier for the product.
            tests:
              - not_null
              - unique
          - name: NAME
            description: Product name.
          - name: SAFETYSTOCKLEVEL
            description: Minimum stock level to maintain safety.
          - name: PRODUCTSUBCATEGORYID
            description: Identifier for the product subcategory.

      - name: productcategory
        description: This table contains information about product categories.
        columns:
          - name: PRODUCTCATEGORYID
            description: Unique identifier for the product category.
            tests:
              - not_null
              - unique
          - name: NAME
            description: Name of the product category.

      - name: productinventory
        description: This table contains information about product inventory.
        columns:
          - name: PRODUCTID
            description: Unique identifier for the product.
            tests:
              - not_null
          - name: QUANTITY
            description: Quantity of the product in stock.

      - name: productsubcategory
        description: This table contains information about product subcategories.
        columns:
          - name: PRODUCTSUBCATEGORYID
            description: Unique identifier for the product subcategory.
            tests:
              - not_null
              - unique
          - name: PRODUCTCATEGORYID
            description: Identifier for the associated product category.
          - name: NAME
            description: Name of the product subcategory.

      - name: salesorderdetail
        description: This table contains information about sales order item details.
        columns:
          - name: SALESORDERID
            description: Foreign Key for the sales order header.
          - name: PRODUCTID
            description: Product sold in the order.
          - name: ORDERQTY
            description: Quantity of the product sold.
          - name: UNITPRICE
            description: Unit price of the product.
          - name: UNITPRICEDISCOUNT
            description: Discount applied per unit.
          - name: SPECIALOFFERID
            description: Identifier for the special offer applied.

      - name: salesorderheader
        description: This table contains information about sales orders, including customer and shipping details.
        columns:
          - name: SALESORDERID
            description: Unique identifier for the sales order.
            tests:
              - not_null
              - unique
          - name: ORDERDATE
            description: Date when the order was placed.
          - name: SUBTOTAL
            description: Total value of items before tax and freight.
          - name: TAXAMT
            description: Tax amount for the order.
          - name: FREIGHT
            description: Shipping cost for the order.
          - name: TOTALDUE
            description: Total amount due for the order.
          - name: CUSTOMERID
            description: Identifier for the associated customer.
          - name: TERRITORYID
            description: Region for the order.
          - name: SHIPMETHODID
            description: Identifier fot the shipping method used for the order.
          - name: CREDITCARDID
            description: Identifier fot thepayment method (credit card).

      - name: salesorderheadersalesreason
        description: This table associates sales orders with reasons for the sale.
        columns:
          - name: SALESORDERID
            description: Identifier for the sales order (foreign key).
          - name: SALESREASONID
            description: Identifier for the reason.

      - name: salesperson
        description: This table contains information about salespeople.
        columns:
          - name: BUSINESSENTITYID
            description: Unique identifier for the salesperson.
          - name: TERRITORYID
            description: Region associated with the salesperson.

      - name: salesreason
        description: This table lists reasons for sales.
        columns:
          - name: SALESREASONID
            description: Unique identifier for the sales reason.
            tests:
              - not_null
              - unique
          - name: NAME
            description: Reason for the sale (e.g., marketing, promotion).

      - name: salesterritory
        description: This table defines sales territories.
        columns:
          - name: TERRITORYID
            description: Unique identifier for the territory.
          - name: NAME
            description: Name of the territory.
          - name: GEOGRAPHICALREGION
            description: Name  of geographical region.
          - name: COUNTRYREGIONCODE
            description: Country or region associated with the territory.
          - name: SALESYTD
            description: Year-to-date sales total.
          - name: SALESLASTYEAR
            description: Last year sales total.
          - name: COSTYTD
            description: Year-to-date cost total.
          - name: COSTLASTYEAR
            description: Last year cost total.

      - name: shipmethod
        description: This table contains information about shipping methods available for orders.
        columns:
          - name: SHIPMETHODID
            description: Identifier to the shipping method used for the order.
          - name: NAME
            description:  Shipping method used for the order.

      - name: specialoffer
        description: This table contains information about promotional offers.
        columns:
          - name: SPECIALOFFERID
            description: Unique identifier for the promotional offer.
          - name: TYPE
            description: category of the promotion.
          - name: CATEGORY
            description: If the promotion is from reseller or customer.

      - name: specialofferproduct
        description: This table associates products with promotional offers.
        columns:
          - name: SPECIALOFFERID
            description: Identifier for the promotional offer.
          - name: PRODUCTID
            description: Identifier for the associated product.

      - name: stateprovince
        description: This table contains information about states or provinces in different countries.
        columns:
          - name: STATEPROVINCEID
            description: Unique identifier for the state/province.
          - name: COUNTRYREGIONCODE
            description: Associated country or region.
          - name: TERRITORYID
            description: Region identifier for the state/province.
          - name: NAME
            description: Name of de state/province.
          - name: ISONLYSTATEPROVINCEFLAG
            description: If is only statate province or not.

      - name: store
        description: This table contains information about stores acting as customers.
        columns:
          - name: BUSINESSENTITYID
            description: Unique identifier for the store.
          - name: NAME
            description: Name of the store.